# -*- coding: utf-8 -*-
"""assignment_statement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15O2wQ2V_ZTvkR9p39As5XxJGjxABE9FY
"""

var1 = 10     # an assignment statement in python