# -*- coding: utf-8 -*-
"""comments.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15O2wQ2V_ZTvkR9p39As5XxJGjxABE9FY
"""

#   This is a comment
#   print name of the course

print('Welcome to OOP Course')


"""This is also a
an example of
multi-line comments"""