# -*- coding: utf-8 -*-
"""doc string comments.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15O2wQ2V_ZTvkR9p39As5XxJGjxABE9FY
"""

def sum(num):
    """Function to the values"""
    return 2+num

print(sum.__doc__)