# -*- coding: utf-8 -*-
"""multiline statements.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15O2wQ2V_ZTvkR9p39As5XxJGjxABE9FY
"""

temp = (10 + 32 + 53 +
    40 + 52 + 46 +
    27 + 68 + 59)


car_Colours = ['red',
                'blue',
                'green']


a = 1; b = 2; c = 3

print('colors',car_Colours)
print('sum is',temp)