# -*- coding: utf-8 -*-
"""operators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MUVKqNonqI_VLXhf9Y-snCdGbBmHoAgQ
"""

m = 15
n = 4

# Output: m + n = 19
print('m + n =',m+n)

# Output: m - n = 11
print('m - n =',m-n)

# Output: m * n = 60
print('m * n =',m*n)

# Output: m / n = 3.75
print('m / n =',m/n)

a = 10
b = 12

# Output: a > b is False
print('a > b is',a>b)

# Output: a < b is True
print('a < b is',a<b)

# Output: a == b is False
print('a == b is',a==b)

# Output: a != b is True
print('a != b is',a!=b)

# Output: a >= b is False
print('a >= b is',a>=b)

# Output: a <= b is True
print('a <= b is',a<=b)

m = True
n = False

print('m and n is',m and n)

print('x or y is',x or y)

print('not x is',not x)

x=10
y= 4
x & y = 0 (0000 0000)
x ^ y = 14 (0000 1110)
x << 2 = 40 (0010 1000)
x >> 2 = 2 (0000 0010)

a=2
a += 5
a %= 5
a **= 5
a //= 5
print(a)

x1 = 10
y1 = 10
x2 = 'Welcome'
y2 = 'Welcome'
x3 = [10,20,30]
y3 = [10,20,30]

# Output: False
print(x1 is not y1)

# Output: True
print(x2 is y2)

# Output: False
print(x3 is y3)

x = 'Hello world'
y = {1:'a',2:'b'}

# Output: True
print('H' in x)

# Output: True
print('hello' not in x)

# Output: True
print(1 in y)

# Output: False
print('a' in y)