# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15O2wQ2V_ZTvkR9p39As5XxJGjxABE9FY
"""



for k in range(1,10) :
    print(k)
    if k == 5 + 4:
        break

if True:
    print('Hello')
    a = 5

if True: print('Hello'); a = 5